### ISSUE TITLE
files seem to be missing

### ISSUE THREAD

**Issue by ExileFox** [bluefoxdev/Godot3.4-building-demo#1]

**Comment by bluefoxdev** [comment]
Can you describe your issue in greater detail?

The repository doesn't seem to be missing any files.

**Comment by ExileFox** [comment]
Godot log:
res://main_scene.gd:4 - Parse Error: Preload file "res://wall.tscn" does not exist.
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://main_scene.gd" with error "Parse error". (User)
  Cannot open file 'res://placement.tscn'.
  Failed loading resource: res://placement.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:626 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).

**Comment by bluefoxdev** [comment]
Hi! Very sorry about this the repo was indeed missing files.

all files are now included, thank you for bringing this to my attention!
